### ISSUE TITLE
Code `pre` has bad css for lightmode

### ISSUE THREAD

**Issue by ikshyza** [friendofsvelte/tipex#4]
While using your editor, it has some issues like this one. I am mostly in light mode, so please fix.

![image](https://github.com/friendofsvelte/tipex/assets/120033434/5d564bf8-14c7-421b-8759-b57138d30178)

By the way, I did this to temporarily fix the issue:
```css
    .html-editor :global(.tipex-editor .tipex-content-section pre) {
        border-radius: 12px;
    }

    
    .html-editor :global(.tipex-editor .tipex-content-section pre code) {
        background-color: rgba(240, 248, 255, 0.144);
        color: rgb(255, 255, 255);
    }
```
